<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Role;
use Spatie\Permission\PermissionRegistrar;

/**
 * Seeds the three Smoothware roles. Per-resource permissions are generated by
 * Filament Shield (`php artisan shield:generate`) once Phase 1 resources exist;
 * `super_admin` is Shield's god-mode role and bypasses individual permission
 * checks. In product terms: super_admin = "Admin", plus Sales Manager and
 * Sales Rep.
 */
class RoleSeeder extends Seeder
{
    public const ROLES = [
        'super_admin',   // "Admin" — full system access (Shield bypass)
        'sales_manager',
        'sales_rep',
    ];

    public function run(): void
    {
        app(PermissionRegistrar::class)->forgetCachedPermissions();

        foreach (self::ROLES as $role) {
            Role::findOrCreate($role, 'web');
        }
    }
}
